export type GameLocale = 'en' | 'de';

export const categories: Record<GameLocale, readonly string[]> = {
  en: [
    'Something that is round',
    'Something that is square',
    'Something that is rectangular',
    'Something that is triangular',
    'Something that is soft',
    'Something that is hard',
    'Something that is cold',
    'Something that is hot',
    'Something that is sweet',
    'Something that is sour',
    'Something that is salty',
    'Something that is bitter',
    'Something that is spicy',
    'Something that is noisy',
    'Something that is quiet',
    'Something that is shiny',
    'Something that is dull',
    'Something that is light (weight)',
    'Something that is heavy',
    'Something that floats',
    'Something that sinks',
    'Something that flies',
    'Something that swims',
    'Something that runs',
    'Something that grows',
    'Something that melts',
    'Something that freezes',
    'Something you can wear',
    'Something you can read',
    'Something you can write with',
    'Something you can sit on',
    'Something in a kitchen',
    'Something in a bathroom',
    'Something in a bedroom',
    'Something in a classroom',
    'Something in a toolbox',
    'Something in a garden',
    'Something at the beach',
    'Something at the park',
    'Something on a farm',
    'Something in a hospital',
    'Something in a supermarket',
    'Something in space',
    'Something underground',
    'Something with wheels',
    'Something with wings',
    'Something with a tail',
    'Something with stripes',
    'Something with spots',
    'Something that is transparent',
    'Something that is translucent',
    'Something that is opaque',
    'Something smaller than a house',
    'Something larger than a car',
    'Something that uses electricity',
    'Something that uses batteries',
    'Something made of wood',
    'Something made of metal',
    'Something made of plastic',
    'Something made of glass',
    'Something made of fabric',
    'Something that is a tool',
    'Something that is a toy',
    'Something that is a fruit',
    'Something that is a vegetable',
    'Something that is a drink',
    'Something that is a dessert',
    'Something you can cook',
    'Something you can bake',
    'Something that measures time',
    'Something that shows numbers',
    'Something that makes music',
    'Something that makes light',
    'Something that makes heat',
    'Something that opens and closes',
    'Something that locks',
    'Something that can be folded',
    'Something that can be inflated',
    'Something that is reusable',
    'Something that is recyclable',
    'Something found in nature',
    'Something found at school',
    'Something found in an office',
    'Something used in sports',
    'A job or profession',
    'A place in a city',
    'A means of transport',
    'An animal that can fly',
    'An animal that can swim',
    'An animal that is a pet',
    'An animal that lives in the forest',
    'An animal that lives in the desert',
    'A musical instrument',
    'A type of clothing',
    'A household appliance',
    'Something round that rolls',
    'Something used for cleaning',
    'Something used for learning',
    'Something used for safety',
    'Something used for communication',
    'Something that smells good',
    'Something that smells bad',
  ],
  de: [
    'Etwas, das rund ist',
    'Etwas, das quadratisch ist',
    'Etwas, das rechteckig ist',
    'Etwas, das dreieckig ist',
    'Etwas, das weich ist',
    'Etwas, das hart ist',
    'Etwas, das kalt ist',
    'Etwas, das heiß ist',
    'Etwas, das süß ist',
    'Etwas, das sauer ist',
    'Etwas, das salzig ist',
    'Etwas, das bitter ist',
    'Etwas, das scharf ist',
    'Etwas, das laut ist',
    'Etwas, das leise ist',
    'Etwas, das glänzend ist',
    'Etwas, das matt ist',
    'Etwas, das leicht ist (Gewicht)',
    'Etwas, das schwer ist',
    'Etwas, das schwebt',
    'Etwas, das sinkt',
    'Etwas, das fliegt',
    'Etwas, das schwimmt',
    'Etwas, das rennt',
    'Etwas, das wächst',
    'Etwas, das schmilzt',
    'Etwas, das gefriert',
    'Etwas, das man tragen kann',
    'Etwas, das man lesen kann',
    'Etwas, womit man schreiben kann',
    'Etwas, auf dem man sitzen kann',
    'Etwas aus der Küche',
    'Etwas aus dem Badezimmer',
    'Etwas aus dem Schlafzimmer',
    'Etwas aus dem Klassenzimmer',
    'Etwas aus dem Werkzeugkasten',
    'Etwas aus dem Garten',
    'Etwas vom Strand',
    'Etwas aus dem Park',
    'Etwas vom Bauernhof',
    'Etwas aus dem Krankenhaus',
    'Etwas aus dem Supermarkt',
    'Etwas aus dem Weltraum',
    'Etwas aus dem Untergrund',
    'Etwas mit Rädern',
    'Etwas mit Flügeln',
    'Etwas mit Schwanz',
    'Etwas mit Streifen',
    'Etwas mit Punkten',
    'Etwas, das transparent ist',
    'Etwas, das halbtransparent ist',
    'Etwas, das undurchsichtig ist',
    'Etwas, das kleiner als ein Haus ist',
    'Etwas, das größer als ein Auto ist',
    'Etwas, das Strom benutzt',
    'Etwas, das Batterien benutzt',
    'Etwas aus Holz',
    'Etwas aus Metall',
    'Etwas aus Kunststoff',
    'Etwas aus Glas',
    'Etwas aus Stoff',
    'Etwas, das ein Werkzeug ist',
    'Etwas, das ein Spielzeug ist',
    'Etwas, das eine Frucht ist',
    'Etwas, das ein Gemüse ist',
    'Etwas, das ein Getränk ist',
    'Etwas, das ein Dessert ist',
    'Etwas, das man kochen kann',
    'Etwas, das man backen kann',
    'Etwas, das die Zeit misst',
    'Etwas, das Zahlen anzeigt',
    'Etwas, das Musik macht',
    'Etwas, das Licht erzeugt',
    'Etwas, das Wärme erzeugt',
    'Etwas, das sich öffnen und schließen lässt',
    'Etwas, das man abschließen kann',
    'Etwas, das man zusammenklappen kann',
    'Etwas, das man aufpumpen kann',
    'Etwas, das wiederverwendbar ist',
    'Etwas, das recycelbar ist',
    'Etwas, das man in der Natur findet',
    'Etwas, das man in der Schule findet',
    'Etwas, das man im Büro findet',
    'Etwas, das im Sport benutzt wird',
    'Ein Beruf',
    'Ein Ort in einer Stadt',
    'Ein Verkehrsmittel',
    'Ein Tier, das fliegen kann',
    'Ein Tier, das schwimmen kann',
    'Ein Haustier',
    'Ein Tier, das im Wald lebt',
    'Ein Tier, das in der Wüste lebt',
    'Ein Musikinstrument',
    'Ein Kleidungsstück',
    'Ein Haushaltsgerät',
    'Etwas, das rund ist und rollt',
    'Etwas, das zum Putzen benutzt wird',
    'Etwas, das zum Lernen benutzt wird',
    'Etwas, das der Sicherheit dient',
    'Etwas, das zur Kommunikation benutzt wird',
    'Etwas, das gut riecht',
    'Etwas, das schlecht riecht',
  ],
};

export const teamEmojis = [
  '🐬',
  '🚀',
  '👑',
  '⭐',
  '🦊',
  '🦄',
  '🐙',
  '🐢',
  '🦁',
  '🤖',
  '👽',
  '👾',
] as const;

export const letterWeights = {
  A: 8,
  B: 6,
  C: 3,
  D: 4,
  E: 10,
  F: 2,
  G: 3,
  H: 4,
  I: 7,
  J: 1,
  K: 2,
  L: 5,
  M: 4,
  N: 6,
  O: 6,
  P: 3,
  Q: 1,
  R: 6,
  S: 8,
  T: 6,
  U: 3,
  V: 1,
  W: 2,
  Z: 1,
} as const;

export const copy = {
  en: {
    setupTitle: 'Build your teams',
    setupHint: 'One device, one judge, plenty of fast answers.',
    passAndPlay: 'Pass & play',
    howToPlay: 'How it works',
    ruleLetter: 'Draw a letter',
    ruleAnswer: 'Name words that fit',
    ruleRace: 'Reach the finish first',
    language: 'Game language',
    teams: 'Teams',
    teamName: 'Team name',
    teamEmoji: 'Team emoji',
    removeTeam: 'Remove',
    addTeam: 'Add team',
    startGame: 'Start game',
    practice: '1–4 teams · one-team practice works too',
    ready: 'Ready to play?',
    readyHint: 'Draw a letter when everyone can see the screen.',
    drawLetter: 'Draw the letter',
    currentLetter: 'Your letter',
    currentTeam: 'Current team',
    hiddenPrompt: 'The first category is still hidden',
    holdHint: 'Hold until the card opens and the timer starts.',
    holdReveal: 'Hold to reveal',
    nameSomething: 'Name something…',
    accept: 'Accept',
    skip: 'Skip',
    skipsLeft: 'skips left',
    seconds: 'seconds',
    position: 'Position',
    start: 'Start',
    finish: 'Finish',
    board: 'Game board',
    endGame: 'End game',
    endTitle: 'End this game?',
    endDescription: 'All team positions and the current round will be lost.',
    cancel: 'Keep playing',
    confirm: 'End game',
    winnerEyebrow: 'We have a winner',
    winnerTitle: 'takes the crown!',
    playAgain: 'Play again',
    nextUp: 'Next up',
    rules: 'Match the category and start with the letter. The judge decides.',
  },
  de: {
    setupTitle: 'Stellt eure Teams zusammen',
    setupHint: 'Ein Gerät, eine Jury und jede Menge schnelle Antworten.',
    passAndPlay: 'Gemeinsam spielen',
    howToPlay: 'So funktioniert es',
    ruleLetter: 'Buchstaben ziehen',
    ruleAnswer: 'Passende Wörter nennen',
    ruleRace: 'Als Erste ins Ziel',
    language: 'Spielsprache',
    teams: 'Teams',
    teamName: 'Teamname',
    teamEmoji: 'Team-Symbol',
    removeTeam: 'Entfernen',
    addTeam: 'Team hinzufügen',
    startGame: 'Spiel starten',
    practice: '1–4 Teams · Üben mit einem Team geht auch',
    ready: 'Bereit zum Spielen?',
    readyHint: 'Zieht einen Buchstaben, sobald alle auf den Bildschirm schauen.',
    drawLetter: 'Buchstaben ziehen',
    currentLetter: 'Euer Buchstabe',
    currentTeam: 'Aktuelles Team',
    hiddenPrompt: 'Die erste Kategorie ist noch verdeckt',
    holdHint: 'Gedrückt halten, bis die Karte erscheint und die Zeit läuft.',
    holdReveal: 'Zum Aufdecken halten',
    nameSomething: 'Nennt etwas…',
    accept: 'Gilt',
    skip: 'Weiter',
    skipsLeft: 'Joker übrig',
    seconds: 'Sekunden',
    position: 'Feld',
    start: 'Start',
    finish: 'Ziel',
    board: 'Spielbrett',
    endGame: 'Spiel beenden',
    endTitle: 'Dieses Spiel beenden?',
    endDescription: 'Alle Positionen und die aktuelle Runde gehen verloren.',
    cancel: 'Weiterspielen',
    confirm: 'Spiel beenden',
    winnerEyebrow: 'Wir haben ein Gewinnerteam',
    winnerTitle: 'holt sich die Krone!',
    playAgain: 'Nochmal spielen',
    nextUp: 'Als Nächstes',
    rules:
      'Die Antwort muss zur Kategorie passen und mit dem Buchstaben beginnen. Die Jury entscheidet.',
  },
} as const;

export type GameCopy = (typeof copy)[GameLocale];
