/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_arcananode_free: (a: number, b: number) => void;
export const arcananode_endpoint_id: (a: number, b: number) => void;
export const arcananode_events: (a: number) => number;
export const arcananode_request: (a: number, b: number, c: number, d: number, e: number) => number;
export const arcananode_respond: (a: number, b: number, c: bigint, d: number, e: number) => void;
export const arcananode_spawn: () => number;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: number) => number;
export const intounderlyingbytesource_start: (a: number, b: number) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: number) => number;
export const intounderlyingsink_close: (a: number) => number;
export const intounderlyingsink_write: (a: number, b: number) => number;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: number) => number;
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const __wasm_bindgen_func_elem_13696: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_13701: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_5062: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_1647: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_6700: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_4843: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_5965: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_6007: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_13566: (a: number, b: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_export5: (a: number, b: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
